#!/usr/bin/env python
import sys
import datetime

base = datetime.datetime.strptime(sys.argv[1], "%Y-%m-%d")
numdays = int(sys.argv[2])

for x in range(0, numdays):
    print (base - datetime.timedelta(days=x)).strftime("%Y-%m-%d")
